### ISSUE TITLE
The binaries provided with cygwin are not up to date

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Agent-Windows#11]
A friend of mine made an addon ( @own3mall  this is when I found myself the other issue we talked about, this one is another one found because of the addon install decompress fail, we then discover another bug in cygwin unzip this way), with a big file of around 5GB, with post install script to manipulate the zip afterwards with "unzip" but his post script failed, file didn't extract correctly. I then suggested to try his post install commands from cyg terminal, same problem the "unzip -o file.zip" didn't extract correctly the file (no error but only a small part of file extracted). Then I suggested to look at the bin/unzip.exe binary, it was very old, he then downloaded a cygwin archive (will try to grab the link later, I forgot to ask him), where he had unzip.exe inside, which was also very old but size was different 300KB for the recent one in his archive, versus around 150KB for the provided one in cygwin. He replaced the cygwin one in the bin folder with this new one, then typed same command in cyg terminal, and it worked correctly, his post install script in his addon, using unzip was also working now. So I think the binaries provided in OGP installer for Windows are maybe not to the latest version and may need to be updated.

**Comment by Zorrototo** [comment]
www.paehl.com/open_source/downloads/unzip.7z here is where he took the unzip.exe that worked correctly for his big zip64 file.

**Comment by own3mall** [comment]
If you ever get that large file, please send it my way.  Until then, I'm closing this issue :)
