### ISSUE TITLE
Fresh OGP install is unable to shutdown game servers

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Agent-Windows#18]
Titles says it all.

Tested on Win10 and 2k12 and issue confirmed.

My guess is that only recent installation are affected, probably because of a change in Easy Installers or the dependencies the Easy Installer installs in the process, as nothing really changed in Agent code.

related thread on forum https://www.opengamepanel.org/forum/viewthread.php?thread_id=6805&pid=36162#post_36160

**Comment by Zorrototo** [comment]
Agent Setup log: https://pastebin.com/Q4brVgNM
Panel Setup log: https://pastebin.com/AN9hDeQh

**Comment by Zorrototo** [comment]
DieFem suggested on forum it may be related to an issue in the installed screen package, maybe a good lead to the issue with OGP unable to properly shutdown the game servers on Windows.

**Comment by own3mall** [comment]
Should be fixed by https://github.com/OpenGamePanel/OGP-Agent-Windows/commit/3bf2aabc3c5ab5d55fe52a0cb959b824ec05cf7a

**Comment by Zorrototo** [comment]
Can confirm a fresh Windows install now properly closes game servers.
