### ISSUE TITLE
Create a Ready2Run version out of the box 

### ISSUE THREAD

**Issue by BestNoob** [OpenGamePanel/OGP-Agent-Windows#25]
Instead of installing and using cyg why dont u provide a ready2run out of the box packet ?

**Comment by own3mall** [comment]
Because OGP wasn't even supposed to run on Windows.  The fact that it currently runs as well as it does on Windows via Cygwin is amazing!  Feel free to create a Windows version that doesn't use cygwin for us to release.  :+1:
