### ISSUE TITLE
Save User Credentials

### ISSUE THREAD

**Issue by Sh4d0wless** [OpenGamePanel/OGP-Agent-Windows#26]
cygstart cmd /c "runas **/savecred** /profile /user:cyg_server \"%WD%\bin\bash.exe %WD%\bin\ogp_agent -pidfile /OGP/ogp_agent_run.pid\""

will be better to add /savecred

**Comment by own3mall** [comment]
Please post things like this in the forum at https://opengamepanel.org

There you can post a thread and describe why you think this is needed.
