### ISSUE TITLE
couldnt start OGP Agent:  cannot assign reuested address at ./ogp_agent.pl Line 271

### ISSUE THREAD

**Issue by ghost** [OpenGamePanel/OGP-Agent-Windows#7]
couldnt start OGP Agent:  cannot assign reuested address at ./ogp_agent.pl Line 271

**Comment by Zorrototo** [comment]
Spamming my PM box, and GitHub issues when I told you multiple times to use the forum will not speed up the process at all... Also if you want support give the most informations possible, of course on the forum.

**Comment by ghost** [comment]
I'm running on the windows server 2015 around maybe that is why it doesnt work

**Comment by own3mall** [comment]
Use the forum for help and support.   Make sure no other process is using the same port as OGP.

**Comment by Furanzou** [comment]
same problem how do i fix it
